# -*- coding: utf-8 -*-
"""heart_disease _plot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kzXgVl0WRAvWzUydwjvMIWrpWbXDnXLo
"""

import pandas as pd

# Load dataset from GitHub (UCI Heart Disease)
url = 'https://raw.githubusercontent.com/samjohn3/heart-disease-analysis/main/heart_disease_data.csv'
df = pd.read_csv(url)

print(df.head())

import seaborn as sns
import matplotlib.pyplot as plt

# Example: Correlation heatmap
plt.figure(figsize=(12, 8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap of Heart Disease Features')
plt.show()

# Example: Chest pain type vs heart disease
sns.countplot(x='cp', hue='target', data=df)
plt.title('Chest Pain Type vs Heart Disease')
plt.xlabel('Chest Pain Type')
plt.ylabel('Count')
plt.show()

"""# New Section"""

sns.pairplot(df, hue='target')
plt.suptitle('Pairwise Relationships by Heart Disease Presence', y=1.02)
plt.show()

sns.boxplot(x='target', y='chol', data=df)
plt.title('Cholesterol Levels by Heart Disease Status')
plt.show()

sns.violinplot(x='target', y='thalach', data=df)
plt.title('Max Heart Rate Distribution by Disease Status')
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X = df.drop('target', axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = RandomForestClassifier()
model.fit(X_train, y_train)

preds = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, preds))